from typing import Any

from sage.rings.finite_rings.element_base import FiniteRingElement
from sage.rings.finite_rings.finite_field_base import FiniteField
from sage.rings.finite_rings.finite_field_constructor import GF as GF


class EllipticCurvePoint:
    def __init__(self, *args: Any) -> None: ...
    def __getitem__(self, i: int) -> FiniteRingElement: ...
    def __add__(self, other: EllipticCurvePoint) -> EllipticCurvePoint: ...
    def __sub__(self, other: EllipticCurvePoint) -> EllipticCurvePoint: ...
    def __rmul__(self, other: int) -> EllipticCurvePoint: ...
    def __neg__(self) -> EllipticCurvePoint: ...
    def is_zero(self) -> bool: ...


class EllipticCurve:
    def __init__(self, field: FiniteField, coefs: list[int]) -> None: ...
    def __call__(self, x: int | FiniteRingElement, y: int | FiniteRingElement) -> EllipticCurvePoint: ...
