name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y clang cmake git libssl-dev libzstd-dev libgtest-dev libbenchmark-dev zlib1g-dev

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure CMake
      run: cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -S $GITHUB_WORKSPACE/lib

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Test
      working-directory: build
      run: ctest -j $(nproc)
